### ISSUE TITLE
proposal: Add support for CNAME

### ISSUE THREAD

**Issue by blijblijblij** [peaceiris/actions-hugo#114]
**Is your feature request related to a problem? Please describe.**
Tried this excellent actions to build and deploy to gh pages but my CNAME was removed

**Describe the solution you'd like**
Support env `CNAME` and pipe it during excection of the action to `./public/CNAME`, something like https://github.com/blijblijblij/blog.blijblijblij.com/blob/master/.github/workflows/main.yml#L32

**Describe alternatives you've considered**
I now manually run a command to populate `./public/CNAME` as per ﻿https://github.com/blijblijblij/blog.blijblijblij.com/blob/master/.github/workflows/main.yml#L22-L24

**Additional context**
-

**Comment by peaceiris** [comment]
Wrong repository, go to [peaceiris/actions-gh-pages](https://github.com/peaceiris/actions-gh-pages).

Did you read the documentation: [How to add CNAME](https://github.com/peaceiris/actions-gh-pages#%EF%B8%8F-how-to-add-cname)?

**Comment by peaceiris** [comment]
And, your project is based on Hugo, you can follow this approach: [static/CNAME | Hugo](https://gohugo.io/hosting-and-deployment/hosting-on-github/#use-a-custom-domain).

I have rejected some proposals similar to this. Do you think it is better to support `.nojekyll`, `BingSiteAuth.xml`, and `robots.txt` as options? Those files should be managed as static files, not options. The same may be said for `CNAME`.
