### ISSUE TITLE
Latest hugo version

### ISSUE THREAD

**Issue by SirWindfield** [peaceiris/actions-hugo#15]
Hey!

I wrote a custom script some time ago for Travis that would always download the latest Hugo version. I could create a PR that would add that logic to the Dockerfile so you do not have to update each time Hugo releases a new version.

We could also use `HUGO_VERSION` for this logic. If it's `auto`, use the latest version, if not, use the specified version within `HUGO_VERSION`.

What are your thoughts?

**Comment by peaceiris** [comment]
We can use the `master` branch for the latest version of Hugo.

```yaml
uses: peaceiris/actions-hugo@master
```

**Comment by SirWindfield** [comment]
That's not was I was referring to. 
If Hugo updates and uploads a new release, you have to update the Dockerfile too. But what if you would do it like [this](https://github.com/SirWindfield/actions-hugo/blob/81ce82a678c5c36c6672efd83b1bf10f9fdc9ea4/Dockerfile#L14)?

This will always download the latest version of Hugo.

**Comment by peaceiris** [comment]
In this case, how do users set a specific version of Hugo?

> We could also use HUGO_VERSION for this logic. If it's auto, use the latest version, if not, use the specified version within HUGO_VERSION.

In my understanding, your suggestion is that:
- `entrypoint.sh` check the `HUGO_VERSION`
- Hugo is downloaded by `entrypoint.sh`

In this method, Hugo will be downloaded every GitHub Actions run and users cannot benefit from the **Docker build cache**.

**Comment by SirWindfield** [comment]
Yes, you are right. Using `entrypoint.sh` wouldn't use the Docker build cache. I changed it a bit: https://github.com/SirWindfield/actions-hugo/blob/master/Dockerfile

This now does use Docker build cache. What do you think?

**Comment by peaceiris** [comment]
LGTM!

We have to add `action.yml` to set `--build-arg HUGO_VERSION='v0.xx.x`

- [args | Metadata syntax for GitHub Actions - GitHub Help](https://help.github.com/en/articles/metadata-syntax-for-github-actions#args)

I want to merge your idea to this repository. Can you submit your Pull Request for us? I will help you to enhance your PR.

**Comment by SirWindfield** [comment]
Yes sure, I can create a PR next week. I am kind of busy right now :smile:

**Comment by peaceiris** [comment]
Ok, thanks ʕ◔ϖ◔ʔ

**Comment by peaceiris** [comment]
Closed by `v2.0.0`
