### ISSUE TITLE
How to publish from gh-pages branch

### ISSUE THREAD

**Issue by rishabh-parekh** [peaceiris/actions-hugo#277]
**Describe the bug**
I used this in Github action/workflow in my repo, and though the workflow was successful, I wasn't able to see site on my github pages. Hence I commented the deploy step and of the job, and used the manual approach as explained in this page (https://gohugo.io/hosting-and-deployment/hosting-on-github/) 

**To Reproduce**
Here is my repo and workflow. 
https://github.com/rishabh-parekh/monk/tree/master/.github/workflows

I had tried Git Hub pages on both master and gh-pages branch, but on any commit to the master, I didn't see the website. 

Is there was way to debug the action, to know where it is deploying. I am probably missing some doc/step. 

**Expected behavior**
I should have seen my static site on the git hub page. I can see it now using my manual push of the content to the gh-pages branch (https://rishabh-parekh.github.io/monk/#/) 

**Your YAML file**
https://github.com/rishabh-parekh/monk/tree/master/.github/workflows

If there is an example website with the workflow configured, that would be very useful. 

Thanks, Rishabh.

**Comment by rishabh-parekh** [comment]
Closing this issue, I think it is working, not sure what was the reason my action/workflow was failing earlier.

**Comment by peaceiris** [comment]
I think you just forgot to enable the GitHub Pages on your repository.

See the documentation [First Deployment with GITHUB_TOKEN - peaceiris/actions-gh-pages](https://github.com/peaceiris/actions-gh-pages#%EF%B8%8F-first-deployment-with-github_token)
