### ISSUE TITLE
Support asciidoc (asciidoctor)

### ISSUE THREAD

**Issue by reitzig** [peaceiris/actions-hugo#342]
## Is your feature request related to a problem? Please describe.

I use AsciiDoc in my site. I would like to use this GitHub action, but it doesn't seem to contain asciidoctor.

## Describe the solution you'd like

Similar to extended mode, an option to add asciidoctor to this action (assuming it's too heavy a dependency to always include).

## Describe alternatives you've considered

Using another action: the ones I checked seem less refined and maintained than this one.

## Additional context

Additional facilities to add command-line parameters for asciidoctor would be gread, cf 
https://github.com/gohugoio/hugo/pull/6561

**Comment by peaceiris** [comment]
Did you try the following?

```yaml
- run: sudo gem install asciidoctor
```

Also we can use the `apt` or `bundle` to install asciidoctor.

- [asciidoctor/asciidoctor](https://github.com/asciidoctor/asciidoctor)

**Comment by reitzig** [comment]
Ah, _now_ I understand the difference between a Docker-based action and one like yours a little bit better, I think. Thank you!

That seems to work -- basically. asciidoctor in the 18.04 repos is ancient, so  gem it is, with a twist:

```yaml
- name: Setup asciidoctor
        run: |
          sudo gem update --system 3.0.6 # cf. https://github.com/rubygems/rubygems/issues/3068#issuecomment-574775885
          ruby --version
          gem --version
          sudo gem install asciidoctor
```

Unfortunately, my [workaround](https://github.com/reitzig/today-i-learned/blob/master/asciidoctor) for Hugo's ... clumsy handling of external tools doesn't seem to work on Github Actions. :thinking:

**Comment by reitzig** [comment]
Heh, got it. For the benefit of googlers:

```yaml
  - name: Setup asciidoctor
    run: |
      sudo gem update --system 3.0.6
      sudo gem install asciidoctor
      sudo .github/scripts/reroute_asciidoctor.sh
      ruby --version; gem --version; asciidoctor --version
```

With this as `.github/scripts/reroute_asciidoctor.sh`:

```bash
#!/bin/bash

set -eu

binary="$(which asciidoctor)"
binary_orig="${binary}"_orig

if [[ -L "${binary}" ]]; then
    echo "Can not handle links yet"
    exit 1
fi

mv "${binary}" "${binary_orig}"

cat > "${binary}" <<BASH
#!/bin/bash

"${binary_orig}" \
    --attribute=experimental=true \
    --attribute=icons=font \
    "\$@"
BASH
chmod +x "${binary}"

echo "Updated '${binary}' to call '${binary_orig}' with extra parameters."
```

I guess it's easy to pull out the extra parameters so they appear in the workflow YAML instead, but not tonight. :'D

**Comment by peaceiris** [comment]
I reopened this for updating the README.

@reitzig Could you review this pull-request? https://github.com/reitzig/today-i-learned/pull/1

**Comment by reitzig** [comment]
Very cool, thanks for your efforts!

Which change of the README do you have an in mind? Do you need me to do something?

I feel like doing this -- adding asciidoctor to a hugo setup, specifically, with workarounds -- could be a dedicated action. I'd be happy to collaborate!

**Comment by peaceiris** [comment]
We are going to add a new section under [Tips - README.md](https://github.com/peaceiris/actions-hugo#tips) like the section for autoprefixer and postcss-cli. If you will work on this, I'll gladly merge it.

**Comment by reitzig** [comment]
Just to point out the alternative here: https://github.com/reitzig/actions-asciidoctor
