### ISSUE TITLE
renaming: master to main

### ISSUE THREAD

**Issue by philshem** [peaceiris/actions-hugo#418]
## Is your feature request related to a problem? Please describe.

I fully support renaming `master` branch `main`. But I hadn't noticed that Github had done so, and I spent a lot of time debugging the action, not noticing the `main`.

## Describe the solution you'd like

Maybe in the README a short note that `master` is no longer used. Even better would be a #comment in the action itself

```
on:
  push:
    branches:
      - main # formerly master
```
## Describe alternatives you've considered

just an idea so that other people don't lose time. Because the action is waiting for push to the `main` branch, there was no logging, making it harder to debug.

## Additional context

n/a

**Comment by peaceiris** [comment]
Thank you for suggesting this!

I hope this change (#419 ) will help new users of GitHub Actions and [github/roadmap issues #63] will solve this.

[github/roadmap issues #63]: https://github.com/github/roadmap/issues/63
