### ISSUE TITLE
AWS S3 example

### ISSUE THREAD

**Issue by kaihendry** [peaceiris/actions-hugo#464]
Could https://github.com/kaihendry/dabase.com/blob/master/.github/workflows/hugo.yml be improved to use the :latest Hugo?

I'm also curious why it's so different to your examples. Many thanks!

**Comment by peaceiris** [comment]
Do you want to start to use this action?

Since you said that you prefer the Docker approach in [this topic], I introduced the workflow using `container: peaceiris/hugo:v0.x.x`

[this topic]: https://discourse.gohugo.io/t/github-workflow-to-s3-cloudfront-could-if-be-nodejs-free/23359/5

**Comment by kaihendry** [comment]
Sorry, I'm re-evaluating my deployment pipelines, trying to make them less complex! 

My goal now is to:

* not use [ubuntu-latest](https://github.community/t/iterating-on-a-workflow/140695/3?u=kaihendry)
* use the latest hugo

**Comment by peaceiris** [comment]
The `container` statement requires `runs-on: ubuntu-latest` so we cannot delete the `runs-on` statement.

I am providing the latest tag (`peaceiris/hugo:latest`). For the stable CI/CD, I recommend you to pin a certain version of Hugo.

**Comment by kaihendry** [comment]
Hmm there is an issue with peaceiris/hugo:latest https://github.com/kaihendry/dabase.com/commit/6af90ce00b468a00bab9cbc186f79815d566b45e

Ok, I have dejavu:
https://discourse.gohugo.io/t/error-incompletesignature/27025/2

There is no issue https://github.com/gohugoio/hugo/issues?q=is%3Aissue+is%3Aopen+Failed+to+invalidate+CloudFront+CDN%3A+IncompleteSignature%3A

Now I'm thinking how to bisect hugo to find the change that broke CloudFront support!

**Comment by peaceiris** [comment]
I recommend you to ask about it at the [HUGO forum](https://discourse.gohugo.io/) first.

**Comment by kaihendry** [comment]
Er, it was asked? https://discourse.gohugo.io/t/error-incompletesignature/27025/2

**Comment by peaceiris** [comment]
Does the problem still persist today? I see.

Did you check this already? https://github.com/aws/aws-sdk-js/issues/3313#issuecomment-645688555

> can you please check for any white space in your creds?

**Comment by kaihendry** [comment]
Ok, I rotated the credentials and now it works!
https://github.com/kaihendry/dabase.com/blob/master/.github/workflows/hugo.yml
