### ISSUE TITLE
Unable to process command '::add-path::/home/runner/actions_hugo/bin' successfully.

### ISSUE THREAD

**Issue by coderdiaz** [peaceiris/actions-hugo#470]
**Note that an issue which does not follow the template will be closed silently.**

## Describe the bug

The `add-path` command is disabled. Please upgrade to using Environment Files or opt into unsecure command execution by setting the `ACTIONS_ALLOW_UNSECURE_COMMANDS` environment variable to `true`. For more information see: https://github.blog/changelog/2020-10-01-github-actions-deprecating-set-env-and-add-path-commands/

## To Reproduce

1. Use the latest version.
2. Run a workflow with Github actions.
3. GitHub says that the `add-path` command was disabled.

## Expected behavior

Build with `hugo` should work.

## Screenshots
![image](https://user-images.githubusercontent.com/1901273/99438128-fbf33880-28d8-11eb-9d46-5e468c1a6bbc.png)

## Your YAML file

- A link to your repository
- A link to your YAML file

**Comment by peaceiris** [comment]
why don’t you use the latest version?
