### ISSUE TITLE
Build against incorrect Hugo Version

### ISSUE THREAD

**Issue by mwolfaardt** [peaceiris/actions-hugo#473]
**Note that an issue which does not follow the template will be closed silently.**

## Describe the bug
In my yml file I specify the Hugo version to be 0.74.1 but when Github builds my static site it uses Hugo version 0.76.3 that causes the build to fail due to my theme not being compatible with the latest version. 

## To Reproduce

1. In your YML change the property of hugo-version from "latest" to '0.74.1' 
2. Check in your files and create a build
3. View the build output 

## Screenshots

![image](https://user-images.githubusercontent.com/11614412/99902735-b794dd80-2cc8-11eb-93bb-93769a457122.png)

## Your YAML file

- name: Setup Hugo
      uses: peaceiris/actions-hugo@v2.4.13
      with:
        #hugo-version: "latest"
        hugo-version: '0.74.1'
    - name: Build
      working-directory: 'blog/cupofdev'
      run: hugo
    - name: Build And Deploy to public
      id: builddeploy
      uses: Azure/static-web-apps-deploy@v0.0.1-preview

## Additional context

none

**Comment by peaceiris** [comment]
You got the error in the "Build And Deploy to public" step. Please follow the instruction fo `Azure/static-web-apps-deploy`. You can use Hugo of the `Azure/static-web-apps-deploy` action.

- [Tutorial: Publish a Hugo site to Azure Static Web Apps | Microsoft Docs](https://docs.microsoft.com/en-us/azure/static-web-apps/publish-hugo)

**Comment by mwolfaardt** [comment]
Thank you, you are the best! added env to my yaml file and it worked!
