### ISSUE TITLE
Page links and css doesn't work on generated site

### ISSUE THREAD

**Issue by IllustratedMan-code** [peaceiris/actions-hugo#504]
**Note that an issue which does not follow the template will be closed silently.**

## Describe the bug

Css and most page links do not work on generated site. [My Site](https://illustratedman-code.github.io/GuideToCS/), [The Repo](https://github.com/IllustratedMan-code/GuideToCS/tree/gh-pages). Testing the table of contents links results in 404 errors. The css is obviously not being loaded.

## To Reproduce

1. Copied sample .yml file, and committed it to the main branch
2. Github action runs successfully
3. Went to site

## Expected behavior
The CSS from the hugo theme [Docport](https://docport.netlify.app/docport-theme/) would be loaded correctly, and the page links would work as expected.

## Screenshots

![image](https://user-images.githubusercontent.com/60514384/113482881-a1650e00-946e-11eb-8278-a02741ad082c.png)

## Your YAML file
[My Repo](https://github.com/IllustratedMan-code/GuideToCS/tree/main)
[My Yaml](https://github.com/IllustratedMan-code/GuideToCS/blob/b3b2b66fadf5761b6c7333b7121296332090ac5e/.github/workflows/gh-pages.yml)

**Comment by peaceiris** [comment]
Why don't you change the `baseURL`?

**Comment by IllustratedMan-code** [comment]
I changed it, and nothing seemed to happen.

**Comment by peaceiris** [comment]
- https://github.com/peaceiris/test-repo/compare/35703afe0dd1776aa8125f03dbf13c036f1470e2...5433c9cfad656c6d69f4492aae447613bef03f7a
- https://peaceiris.github.io/test-repo/

**Comment by IllustratedMan-code** [comment]
I see it now. Thanks for dealing with me!
