### ISSUE TITLE
gitignore the build directory in master/main?

### ISSUE THREAD

**Issue by bradryanbice** [peaceiris/actions-hugo#515]
**Note that an issue which does not follow the template will be closed silently.**

## Check list before opening this issue

- [x] I read the latest README of this repository.

For users of the GitHub Pages Action:

- [x] I checked [Available Options](https://github.com/peaceiris/actions-gh-pages#options)
- [x] I followed [Tips and FAQs](https://github.com/peaceiris/actions-gh-pages#tips-and-faq)
- [x] I tried [Workflow Examples](https://github.com/peaceiris/actions-gh-pages#examples)

## Describe your question

I am currently pushing my Hugo site changes to master, which is then using this Action to build a Github Page to a `gh-pages` branch, using a `./docs` `publish_dir`.

It seems my site will not build correctly unless I fully build, commit, and push the entire `/docs` `publishDir` in Hugo. Which also means I'm having to track that entire directory with any change to my source.

It seems I'm doing something wrong here, and that should not be necessary. Am I correct, and is there a way to `.gitignore` my `/docs` directory in the `master` branch? Would I use something like `exclude_assets` in this case?

**Comment by peaceiris** [comment]
I think you are having the `docs` folder under Git control. We do not need to put the built files under Git control. As a workaround, you can run `hugo --cleanDestinationDir` to delete `docs` each running.

To remove the `docs` folder from Git control completely, you can run the following commands. 

1. Add `docs` to the `.gitignore` file
2. Run `git rm -r --cached ./docs`
3. Add, commit and push the changes.

**Comment by peaceiris** [comment]
In addition, it may be useful to check the current setting.

![Screen Shot 2021-05-06 at 0 20 35](https://user-images.githubusercontent.com/30958501/117165939-e4652900-ae00-11eb-8769-37b18a26a558.png)

**Comment by bradryanbice** [comment]
Ok, should I not have `publish_dir: ./docs` in my `gh-pages.yml` then?

```
     - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_branch: gh-pages
          publish_dir: ./docs
```

**Comment by peaceiris** [comment]
If your `publishDir` (Hugo's config) is `docs`, keep that workflow.
