### ISSUE TITLE
support: Docsy Theme can not be built.

### ISSUE THREAD

**Issue by Xu-Xihe** [peaceiris/actions-hugo#547]
### Checklist

- [X] I am using the latest version of this action.
- [X] I have read the latest README and followed the instructions.
- [X] I have read the latest GitHub Actions official documentation and learned the basic spec and concepts.

### Describe the bug

I have fork the docsy-example site and just copy the template for it in th README.md file.
I only changed the on: branches from main to master.
But after I pushed,it doesn't work.The Github Actions has showed  me a '×',but I dont now why.

### Relevant links

```markdown
Public repository:https://github.com/Xu-Xihe/docsy-example
YAML config:
YAML workflow:
```

### Relevant log output

Run npm ci
  npm ci
  shell: /usr/bin/bash -e {0}
npm ERR! cipm can only install packages with an existing package-lock.json or npm-shrinkwrap.json with lockfileVersion >= 1. Run an install with npm@5 or later to generate it, then try again.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/runner/.npm/_logs/2021-10-19T14_53_22_563Z-debug.log
Error: Process completed with exit code 1.

### Additional context.

NO.

**Comment by peaceiris** [comment]
Why don't you put your `package-lock.json` under Git control?
