### ISSUE TITLE
Multiple static  folders not working

### ISSUE THREAD

**Issue by keenedge** [peaceiris/actions-hugo#556]
### Checklist

- [X] I am using the latest version of this action.
- [X] I have read the latest README and followed the instructions.
- [X] I have read the latest GitHub Actions official documentation and learned the basic spec and concepts.

### Describe your question

My config.toml  defines two static folder like this: 

   staticDir = ['static','content\projects\home-lab\static']

Locally hugo builds the second static folder into the root of the "public" folder.  which works correctly.

when this action build and deploys my pages it does not build the second static folder into the output files.

 

### Relevant links

```markdown
Public repository: https://github.com/keenedge/keenedge.github.io

hugo config: https://github.com/keenedge/keenedge.github.io/blob/main/config.toml

YAML config:    
YAML workflow: https://github.com/keenedge/keenedge.github.io/blob/main/.github/workflows/gh-pages.yml
```

### Relevant log output

Sorry, I don't know where to find the action log file

### Additional context.

Pleae let me know if you need any other info

**Comment by peaceiris** [comment]
Your local environment is Windows and the CI environment is Linux (Ubuntu).

```diff
baseURL = "https://kb.isle.net/"
languageCode = "en-us"
title = "My New Hugo Site"
- staticDir = ['static','content\projects\home-lab\static']
+ staticDir = ['static','content/projects/home-lab/static']
```

Please use `/` for Unix-like systems as the file path format, use `\` for Windows.

**Comment by keenedge** [comment]
OMG.  I can't believe it.  You are sooo right.   Thanks very much.
