### ISSUE TITLE
support: fatal: unsafe repository

### ISSUE THREAD

**Issue by kaihendry** [peaceiris/actions-hugo#579]
### Checklist

- [X] I am using the latest version of this action.
- [X] I have read the latest README and followed the instructions.
- [X] I have read the latest GitHub Actions official documentation and learned the basic spec and concepts.

### Describe your question

Build failure when it worked before: https://github.com/kaihendry/dabase.com/runs/6157428721?check_suite_focus=true

### Relevant links

```markdown
https://github.com/kaihendry/dabase.com/blob/master/.github/workflows/hugo.yml
```

### Relevant log output

```
hugo v0.97.3-078053a43d746a26aa3d48cf1ec7122ae78a9bb4+extended linux/amd64 BuildDate=2022-04-18T17:22:19Z VendorInfo=gohugoio
ERROR 2022/04/25 12:31:10 Failed to read Git log: fatal: unsafe repository ('/__w/dabase.com/dabase.com' is owned by someone else)
To add an exception for this directory, call:

	git config --global --add safe.directory /__w/dabase.com/dabase.com
WARN 2022/04/25 12:31:11 .File.BaseFileName on zero object. Wrap it in if or with: {{ with .File }}{{ .BaseFileName }}{{ end }}
Error: Error building site: logged 1 error(s)
```

### Additional context.

Thank you for this project!

**Comment by peaceiris** [comment]
Please try actions/checkout@v3

**Comment by kaihendry** [comment]
Same issue? https://github.com/kaihendry/dabase.com/runs/6168349857?check_suite_focus=true

**Comment by peaceiris** [comment]
It seems to should be fixed in the `peaceiris/hugo` docker image.
As a workaround, we can run `git config --global --add safe.directory /` before hugo step.

**Comment by peaceiris** [comment]
https://github.com/peaceiris/hugo-extended-docker/pull/79

**Comment by kaihendry** [comment]
I just re-ran and it still fails... Do I just wait? :grimacing:  

https://github.com/kaihendry/dabase.com/runs/6168545815?check_suite_focus=true

**Comment by peaceiris** [comment]
You can try the image `ghcr.io/peaceiris/hugo:test`

**Comment by peaceiris** [comment]
Or `peaceiris/hugo:test`

**Comment by kaihendry** [comment]
Still fails? https://github.com/kaihendry/dabase.com/runs/6170692004?check_suite_focus=true

**Comment by peaceiris** [comment]
Currently, we can add the following command before hugo building to avoid the error.

This looks like the current better measure since it is difficult to know a GITHUB_WORKSPACE directory when a Docker image is built.

cf. [Git security vulnerability announced | The GitHub Blog](https://github.blog/2022-04-12-git-security-vulnerability-announced/)

```yaml
jobs:
  build:
    runs-on: ubuntu-20.04
    container: peaceiris/hugo:v0.97.3
    steps:
      - uses: actions/checkout@v3
      - name: Build and Deploy
        run: |
          git config --global --add safe.directory ${GITHUB_WORKSPACE}
          hugo
```

**Comment by kaihendry** [comment]
Thanks for your help! I'll buy you a beer in Singapore https://github.com/kaihendry/dabase.com/runs/6186503865?check_suite_focus=true
