### ISSUE TITLE
support: Unexpected warning about the used NodeJS version 

### ISSUE THREAD

**Issue by nielsbasjes** [peaceiris/actions-hugo#611]
### Checklist

- [X] I am using the latest version of this action.
- [X] I have read the latest README and followed the instructions.
- [X] I have read the latest GitHub Actions official documentation and learned the basic spec and concepts.

### Describe your question

My job gives a warning

    Node.js 12 actions are deprecated. 
    For more information see: https://github.blog/changelog/2022-09-22-github-actions-all-actions-will-begin-running-on-node16-instead-of-node12/. 
    Please update the following actions to use Node.js 16: peaceiris/actions-hugo, peaceiris/actions-gh-pages

### Relevant links

```markdown
Public repository:
https://github.com/nielsbasjes/yauaa/blob/d1ee16088b5fe5a8142783097cc738d90f95f579/.github/workflows/website.yml

YAML config:
YAML workflow:


name: Documentation Website

on:
  push:
    branches:
      - main  # Set a branch to deploy
  pull_request:

jobs:
  deploy:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: true  # Fetch Hugo themes (true OR recursive)
          fetch-depth: 0    # Fetch all history for .GitInfo and .Lastmod

      - name: Setup Hugo
        uses: peaceiris/actions-hugo@v2
        with:
          hugo-version: 'latest'
          # extended: true

      - name: Build
        run: cd documentation && hugo --minify

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        if: github.ref == 'refs/heads/main'
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./documentation/public
```
```


### Relevant log output

This warning message is shown:


    Node.js 12 actions are deprecated. 
    For more information see: https://github.blog/changelog/2022-09-22-github-actions-all-actions-will-begin-running-on-node16-instead-of-node12/. 
    Please update the following actions to use Node.js 16: peaceiris/actions-hugo, peaceiris/actions-gh-pages




### Additional context.

This workflow has run successfully for more than 8 months.
Apparently this is cause by a change in github:

https://github.blog/changelog/2022-09-22-github-actions-all-actions-will-begin-running-on-node16-instead-of-node12/

**Comment by peaceiris** [comment]
Thanks, I will release the next major version of this action with Nodo.js 16

**Comment by nielsbasjes** [comment]
I expect this to be an issue for all github actions because I have also seen this in a different project (same warning about actions/checkout and actions/checkout):

    Node.js 12 actions are deprecated. 
    For more information see: https://github.blog/changelog/2022-09-22-github-actions-all-actions-will-begin-running-on-node16-instead-of-node12/. 
    Please update the following actions to use Node.js 16: actions/checkout, actions/checkout

**Comment by soleo** [comment]
@nielsbasjes Could I help out here? I am having the same issue with a few github actions with my own site as well.

**Comment by nielsbasjes** [comment]
Other than the instructions on the page provided by Github I do not have additional information.

**Comment by soleo** [comment]
@nielsbasjes Do you wanna give `soleo/actions-hugo@v3.0.0` a try? I made the changes to upgrade to node16 recently and tried to use it for my own website.

**Comment by soleo** [comment]
@peaceiris Feel free to take a look to see if it make sense to you

**Comment by nielsbasjes** [comment]
> @nielsbasjes Do you wanna give `soleo/actions-hugo@v3.0.0` a try? I made the changes to upgrade to node16 recently and tried to use it for my own website. 
> 
> 

For me it currently is only a warning.
So I'm just going to wait for the release and then let renovate update the version.

**Comment by shenweiyan** [comment]
> @peaceiris Feel free to take a look to see if it make sense to you

I got the same error, and try `soleo/actions-hugo@v3.0.0` , it failed with the same warning too.

**Comment by peaceiris** [comment]
I am planning the next major release from node12 to node16 this weekend.
