### ISSUE TITLE
support: Custom Domain Support

### ISSUE THREAD

**Issue by elibroftw** [peaceiris/actions-hugo#624]
### Checklist

- [X] I am using the latest version of this action.
- [X] I have read the latest README and followed the instructions.
- [X] I have read the latest GitHub Actions official documentation and learned the basic spec and concepts.

### Describe your question

My custom domain is removed every time I push to my default branch. There is no CNAME being created and it screws everything up. Is there a way to use a different branch than `gh-pages`? Something like `hugo-public`? That way github can remember my custom domain. As of now I feel like this action has wasted more time than saved me :(

### Relevant links

```markdown
Public repository: https://github.com/elibroftw/blog.elijahlopez.ca
YAML config: https://github.com/elibroftw/blog.elijahlopez.ca/blob/master/config.yaml
YAML workflow: https://github.com/elibroftw/blog.elijahlopez.ca/actions/runs/3544922088/workflow
```

### Relevant log output

https://pipelines.actions.githubusercontent.com/serviceHosts/80c54f74-035f-451b-a124-6e9500d7690f/_apis/pipelines/1/runs/252/signedlogcontent/2?urlExpires=2022-11-25T02%3A57%3A39.5388191Z&urlSigningMethod=HMACV1&urlSignature=VEl%2B%2FhtmFX80qunhZLb60rVt%2B2CUS2%2FA2X5%2FG1Fd0%2FA%3D

### Additional context.

...

**Comment by elibroftw** [comment]
https://github.com/elibroftw/blog.elijahlopez.ca/blob/master/.github/workflows/gh-pages.yml

**Comment by peaceiris** [comment]
- Option 1 `cname` input https://github.com/peaceiris/actions-gh-pages#%EF%B8%8F-add-cname-file-cname
- Option 2 `static/CNAME` https://gohugo.io/hosting-and-deployment/hosting-on-github/#use-a-custom-domain
