### ISSUE TITLE
proposal: update node to a more recent version

### ISSUE THREAD

**Issue by retorquere** [peaceiris/actions-hugo#642]
### Checklist

- [X] I am using the latest version of this action.
- [X] I have read the latest README and followed the instructions.
- [X] I have read the latest GitHub Actions official documentation and learned the basic spec and concepts.

### Describe your proposal

update node to a more recent version. GHA is reporting that node 16 actions are deprecated

### Describe the solution you'd like

An update to a newer node version

### Describe alternatives you've considered

Manually installing hugo

### Additional context

None

**Comment by tohn** [comment]
Got this warning as well:

> Node.js 16 actions are deprecated. Please update the following actions to use Node.js 20: peaceiris/actions-hugo@v2.6.0. For more information see: https://github.blog/changelog/2023-09-22-github-actions-transitioning-from-node-16-to-node-20/.

I think https://github.com/peaceiris/actions-hugo/pull/641 does exactly that? And https://github.com/peaceiris/actions-hugo/pull/614 is obsolete now 😉

**Comment by retorquere** [comment]
> I think https://github.com/peaceiris/actions-hugo/pull/641 does exactly that?

Seems like it does.

**Comment by daviddavo** [comment]
But we still need a [release](https://github.com/peaceiris/actions-hugo/releases) so github action's picks it up automatically

**Comment by jesseadams** [comment]
@peaceiris Can we please get a new release?

**Comment by peaceiris** [comment]
https://github.com/peaceiris/actions-hugo/issues/647#issuecomment-2031002966

**Comment by ricomariani** [comment]
peaceiris/actions-hugo@v3 is working for me.  I removed the SHA in my  comment above so nobody will use it by accident.  I will likely delete my fork in a few weeks  just in case someone is still using the workaround SHA.

**Comment by peaceiris** [comment]
Thank you so much @ricomariani!
