### ISSUE TITLE
Action runs are failing with all versions after v2.6.0

### ISSUE THREAD

**Issue by deining** [peaceiris/actions-hugo#644]
### Checklist

- [X] I am using the latest version of this action.
- [X] I have read the latest README and followed the instructions.
- [X] I have read the latest GitHub Actions official documentation and learned the basic spec and concepts.

### Describe your question

I realized that with all commits after version 2.6.0, action runs are failing for my site deployment.

### Relevant links

Public repository: https://github.com/deining/vitalcontrol.de
YAML config: [deploy.yml](https://github.com/deining/vitalcontrol.de/blob/a84c75520a1e03e105e879494881c0b272b75974/.github/workflows/deploy.yml)
YAML workflow: [failed workflow run](https://github.com/deining/vitalcontrol.de/actions/runs/7857181303)

### Relevant log output

With version aadc3a98dfd3437f8f97d436ea91b82a73dc85dd, action run fails:

```
Run peaceiris/actions-hugo@aadc3a98dfd3437f8f97d436ea91b82a73dc85dd
  with:
    hugo-version: 0.122.0
    extended: true
Error: File not found: '/home/runner/work/_actions/peaceiris/actions-hugo/aadc3a98dfd3437f8f97d436ea91b82a73dc85dd/lib/index.js'
```

With version 2.6.0, action run is fine:
```
Run peaceiris/actions-hugo@16361eb4acea8698b220b76c0d4e84e1fd22c61d
  with:
    hugo-version: 0.122.0
    extended: true
Hugo version: 0.122.0
/usr/bin/tar xz --warning=no-unknown-keyword --overwrite -C /home/runner/actions_hugo/_temp -f /home/runner/work/_temp/fe0b9540-1f17-463d-b39b-99bcafe2afbc
/home/runner/actions_hugo/bin/hugo version
hugo v0.122.0-b9a03bd59d5f71a529acb3e33f995e0ef332b3aa+extended linux/amd64 BuildDate=2024-01-26T15:54:24Z VendorInfo=gohugoio
```

### Additional context:

With version [aadc3a98dfd3437f8f97d436ea91b82a73dc85dd](https://github.com/peaceiris/actions-hugo/commit/4910870eaa6a9e51abbbc4996f75b0eadabbbc57), `lib\index.js` was deleted from the repo.

**Comment by ricomariani** [comment]
FWIW it seems that the normal release script creates lib\index.js and then deletes it.  That's just how the release process rolls here.  The consequence is that only the exact SHA for the published released versions are usable.  It seems to be quite intentional.

**Comment by ricomariani** [comment]
peaceiris/actions-hugo@v3 seems to be working now

**Comment by deining** [comment]
Just update to peaceiris/actions-hugo@v3. Deployment worked perfectly fine! Thanks for the update!
Closing this ticket now.
